server:
  port: 8761

spring:
  application:
    name: discovery-service
  profiles:
    active: dev
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
