server:
  port: 8761

spring:
  application:
    name: discovery-service
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
  instance:
    preferIpAddress: true
