server:
  port: 8093

spring:
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
