spring:
  application:
    name: admin
  security:
    user:
      name: admin
      password: admin
  profiles:
    active: dev
  config:
    import: optional:configserver:spring-config-server
  cloud:
    config:
      username: root
      password: s3cr3t
      discovery:
        service-id: spring-config-server
        enabled: true
