server:
  port: 8082

spring:
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

clients:
  producer:
    name: 'producer'


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
