spring:
  security:
    user:
      name: admin
      password: admin
  application:
    name: admin
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      username: root
      password: s3cr3t
